<?php
$data = array (
  0 => 
  array (
    'cat_id' => '16',
    'cat_name' => '公司动态',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '1',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => '',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  1 => 
  array (
    'cat_id' => '14',
    'cat_name' => '今日聚焦',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '2',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => '',
    'has_children' => '0',
    'aricle_num' => '9',
  ),
  2 => 
  array (
    'cat_id' => '18',
    'cat_name' => '行业聚焦',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '3',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => '',
    'has_children' => '0',
    'aricle_num' => '10',
  ),
  3 => 
  array (
    'cat_id' => '13',
    'cat_name' => '生活百科',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '4',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => '',
    'has_children' => '0',
    'aricle_num' => '10',
  ),
  4 => 
  array (
    'cat_id' => '12',
    'cat_name' => '站内快讯',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '5',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => '',
    'has_children' => '0',
    'aricle_num' => '10',
  ),
  5 => 
  array (
    'cat_id' => '4',
    'cat_name' => '开店必备',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '6',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => '',
    'has_children' => '0',
    'aricle_num' => '10',
  ),
  6 => 
  array (
    'cat_id' => '20',
    'cat_name' => '广告354*454',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => '',
    'has_children' => '0',
    'aricle_num' => '5',
  ),
  7 => 
  array (
    'cat_id' => '11',
    'cat_name' => '手机促销',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => '',
    'has_children' => '0',
    'aricle_num' => '11',
  ),
  8 => 
  array (
    'cat_id' => '17',
    'cat_name' => '广告1210*100',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => '',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  9 => 
  array (
    'cat_id' => '1',
    'cat_name' => '系统分类',
    'cat_type' => '2',
    'keywords' => '',
    'cat_desc' => '系统保留分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => '',
    'has_children' => '2',
    'aricle_num' => '0',
  ),
  10 => 
  array (
    'cat_id' => '19',
    'cat_name' => '供货商通知文章',
    'cat_type' => '99',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => '',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  11 => 
  array (
    'cat_id' => '3',
    'cat_name' => '网店帮助分类',
    'cat_type' => '4',
    'keywords' => '',
    'cat_desc' => '网店帮助分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'path_name' => '',
    'has_children' => '5',
    'aricle_num' => '0',
  ),
  12 => 
  array (
    'cat_id' => '2',
    'cat_name' => '网店信息',
    'cat_type' => '3',
    'keywords' => '',
    'cat_desc' => '网店信息分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'path_name' => '',
    'has_children' => '0',
    'aricle_num' => '5',
  ),
  13 => 
  array (
    'cat_id' => '8',
    'cat_name' => '售后服务',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'path_name' => '',
    'has_children' => '0',
    'aricle_num' => '7',
  ),
  14 => 
  array (
    'cat_id' => '5',
    'cat_name' => '新手上路 ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'path_name' => '',
    'has_children' => '0',
    'aricle_num' => '6',
  ),
  15 => 
  array (
    'cat_id' => '9',
    'cat_name' => '关于我们 ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '联系我们 ',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'path_name' => '',
    'has_children' => '0',
    'aricle_num' => '6',
  ),
  16 => 
  array (
    'cat_id' => '10',
    'cat_name' => '购物指南',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'path_name' => '',
    'has_children' => '0',
    'aricle_num' => '7',
  ),
  17 => 
  array (
    'cat_id' => '7',
    'cat_name' => '配送方式 ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '配送与支付 ',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'path_name' => '',
    'has_children' => '0',
    'aricle_num' => '6',
  ),
);
?>