<?php
$data = array (
  0 => 
  array (
    'cat_id' => '1',
    'cat_name' => '食品生鲜',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '1',
    'has_children' => '5',
    'goods_num' => '4',
  ),
  1 => 
  array (
    'cat_id' => '2',
    'cat_name' => '服装服饰',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '2',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '3',
    'cat_name' => '个护化妆',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '3',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '4',
    'cat_name' => '手机数码',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '4',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '5',
    'cat_name' => '家用电器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '5',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '6',
    'cat_name' => '家纺家居',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '6',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  6 => 
  array (
    'cat_id' => '7',
    'cat_name' => '酒类饮料',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '7',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  7 => 
  array (
    'cat_id' => '8',
    'cat_name' => '母婴用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '8',
    'has_children' => '6',
    'goods_num' => '9',
  ),
  8 => 
  array (
    'cat_id' => '14',
    'cat_name' => '进口水果',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '8',
    'goods_num' => '17',
  ),
  9 => 
  array (
    'cat_id' => '13',
    'cat_name' => '糖果巧克力',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '7',
    'goods_num' => '8',
  ),
  10 => 
  array (
    'cat_id' => '9',
    'cat_name' => '牛奶乳品',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '8',
    'goods_num' => '8',
  ),
  11 => 
  array (
    'cat_id' => '10',
    'cat_name' => '坚果炒货',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '13',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '蜜饯果干',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '14',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  13 => 
  array (
    'cat_id' => '60',
    'cat_name' => '箱包馆',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  14 => 
  array (
    'cat_id' => '57',
    'cat_name' => '男装馆',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  15 => 
  array (
    'cat_id' => '55',
    'cat_name' => '女装馆',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  16 => 
  array (
    'cat_id' => '58',
    'cat_name' => '户外鞋服',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  17 => 
  array (
    'cat_id' => '59',
    'cat_name' => '女鞋馆',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  18 => 
  array (
    'cat_id' => '56',
    'cat_name' => '内衣馆',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  19 => 
  array (
    'cat_id' => '113',
    'cat_name' => '香水彩妆',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  20 => 
  array (
    'cat_id' => '111',
    'cat_name' => '身体护肤',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  21 => 
  array (
    'cat_id' => '112',
    'cat_name' => '口腔护理',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  22 => 
  array (
    'cat_id' => '109',
    'cat_name' => '面部护肤',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => '1',
  ),
  23 => 
  array (
    'cat_id' => '110',
    'cat_name' => '洗发护发',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  24 => 
  array (
    'cat_id' => '147',
    'cat_name' => '智能设备',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  25 => 
  array (
    'cat_id' => '144',
    'cat_name' => '热卖手机',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => '4',
  ),
  26 => 
  array (
    'cat_id' => '145',
    'cat_name' => '手机配件',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => '8',
  ),
  27 => 
  array (
    'cat_id' => '146',
    'cat_name' => '数码影音',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => '8',
  ),
  28 => 
  array (
    'cat_id' => '182',
    'cat_name' => '五金家装',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  29 => 
  array (
    'cat_id' => '179',
    'cat_name' => '生活电器',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => '10',
  ),
  30 => 
  array (
    'cat_id' => '180',
    'cat_name' => '厨房电器',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => '8',
  ),
  31 => 
  array (
    'cat_id' => '181',
    'cat_name' => '个护健康',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  32 => 
  array (
    'cat_id' => '178',
    'cat_name' => '大家电',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => '8',
  ),
  33 => 
  array (
    'cat_id' => '311',
    'cat_name' => '生活日用',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  34 => 
  array (
    'cat_id' => '306',
    'cat_name' => '家纺',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => '8',
  ),
  35 => 
  array (
    'cat_id' => '308',
    'cat_name' => '厨具',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => '8',
  ),
  36 => 
  array (
    'cat_id' => '309',
    'cat_name' => '灯具',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  37 => 
  array (
    'cat_id' => '310',
    'cat_name' => '家装软饰',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  38 => 
  array (
    'cat_id' => '307',
    'cat_name' => '家具',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 8,
  ),
  39 => 
  array (
    'cat_id' => '271',
    'cat_name' => '酒水',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  40 => 
  array (
    'cat_id' => '272',
    'cat_name' => '冲调饮品',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  41 => 
  array (
    'cat_id' => '273',
    'cat_name' => '饮料饮品',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  42 => 
  array (
    'cat_id' => '274',
    'cat_name' => '茗茶',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  43 => 
  array (
    'cat_id' => '223',
    'cat_name' => '孕婴洗护',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 9,
  ),
  44 => 
  array (
    'cat_id' => '224',
    'cat_name' => '喂养用品',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  45 => 
  array (
    'cat_id' => '221',
    'cat_name' => '孕婴奶粉',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => '8',
  ),
  46 => 
  array (
    'cat_id' => '225',
    'cat_name' => '车床/床品',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  47 => 
  array (
    'cat_id' => '222',
    'cat_name' => '营养/辅食',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 8,
  ),
  48 => 
  array (
    'cat_id' => '226',
    'cat_name' => '孕妈专区',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  49 => 
  array (
    'cat_id' => '37',
    'cat_name' => '全脂奶',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  50 => 
  array (
    'cat_id' => '34',
    'cat_name' => '酸奶',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  51 => 
  array (
    'cat_id' => '31',
    'cat_name' => '常温奶',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  52 => 
  array (
    'cat_id' => '38',
    'cat_name' => '成人奶粉',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  53 => 
  array (
    'cat_id' => '35',
    'cat_name' => '豆奶',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  54 => 
  array (
    'cat_id' => '32',
    'cat_name' => '乳饮料',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  55 => 
  array (
    'cat_id' => '36',
    'cat_name' => '低脂奶',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  56 => 
  array (
    'cat_id' => '33',
    'cat_name' => '儿童奶',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  57 => 
  array (
    'cat_id' => '46',
    'cat_name' => '杏仁',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  58 => 
  array (
    'cat_id' => '43',
    'cat_name' => '腰果',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  59 => 
  array (
    'cat_id' => '40',
    'cat_name' => '夏威夷果',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  60 => 
  array (
    'cat_id' => '44',
    'cat_name' => '瓜子',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  61 => 
  array (
    'cat_id' => '41',
    'cat_name' => '碧根果',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  62 => 
  array (
    'cat_id' => '45',
    'cat_name' => '花生',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  63 => 
  array (
    'cat_id' => '42',
    'cat_name' => '开心果',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  64 => 
  array (
    'cat_id' => '39',
    'cat_name' => '核桃',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  65 => 
  array (
    'cat_id' => '53',
    'cat_name' => '橄榄',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  66 => 
  array (
    'cat_id' => '50',
    'cat_name' => '芒果干',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  67 => 
  array (
    'cat_id' => '47',
    'cat_name' => '红枣',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  68 => 
  array (
    'cat_id' => '54',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  69 => 
  array (
    'cat_id' => '51',
    'cat_name' => '香蕉干',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  70 => 
  array (
    'cat_id' => '48',
    'cat_name' => '莓类',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  71 => 
  array (
    'cat_id' => '52',
    'cat_name' => '山楂片',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  72 => 
  array (
    'cat_id' => '49',
    'cat_name' => '葡萄干',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  73 => 
  array (
    'cat_id' => '30',
    'cat_name' => '果冻',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  74 => 
  array (
    'cat_id' => '27',
    'cat_name' => '软糖',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  75 => 
  array (
    'cat_id' => '24',
    'cat_name' => '巧克力',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  76 => 
  array (
    'cat_id' => '28',
    'cat_name' => '奶糖',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  77 => 
  array (
    'cat_id' => '25',
    'cat_name' => '口香糖',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  78 => 
  array (
    'cat_id' => '29',
    'cat_name' => 'QQ糖',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  79 => 
  array (
    'cat_id' => '26',
    'cat_name' => '棒棒糖',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  80 => 
  array (
    'cat_id' => '20',
    'cat_name' => '奇异果猕猴桃',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  81 => 
  array (
    'cat_id' => '17',
    'cat_name' => '芒果桃李',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  82 => 
  array (
    'cat_id' => '21',
    'cat_name' => '凤梨蓝莓',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  83 => 
  array (
    'cat_id' => '18',
    'cat_name' => '龙眼荔枝',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  84 => 
  array (
    'cat_id' => '15',
    'cat_name' => '释迦芭乐',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  85 => 
  array (
    'cat_id' => '22',
    'cat_name' => '榴莲山竹',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  86 => 
  array (
    'cat_id' => '19',
    'cat_name' => '小波',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  87 => 
  array (
    'cat_id' => '16',
    'cat_name' => '樱桃车厘子',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  88 => 
  array (
    'cat_id' => '63',
    'cat_name' => '棉麻T恤',
    'measure_unit' => '',
    'parent_id' => '55',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  89 => 
  array (
    'cat_id' => '67',
    'cat_name' => '短外套',
    'measure_unit' => '',
    'parent_id' => '55',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  90 => 
  array (
    'cat_id' => '64',
    'cat_name' => '时尚套装',
    'measure_unit' => '',
    'parent_id' => '55',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  91 => 
  array (
    'cat_id' => '61',
    'cat_name' => '连衣裙',
    'measure_unit' => '',
    'parent_id' => '55',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
  ),
  92 => 
  array (
    'cat_id' => '68',
    'cat_name' => '防晒衫',
    'measure_unit' => '',
    'parent_id' => '55',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  93 => 
  array (
    'cat_id' => '65',
    'cat_name' => '复古旗袍',
    'measure_unit' => '',
    'parent_id' => '55',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  94 => 
  array (
    'cat_id' => '62',
    'cat_name' => '连体裤',
    'measure_unit' => '',
    'parent_id' => '55',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  95 => 
  array (
    'cat_id' => '66',
    'cat_name' => '牛仔裤',
    'measure_unit' => '',
    'parent_id' => '55',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  96 => 
  array (
    'cat_id' => '76',
    'cat_name' => '瘦腿袜',
    'measure_unit' => '',
    'parent_id' => '56',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  97 => 
  array (
    'cat_id' => '73',
    'cat_name' => '男士内裤',
    'measure_unit' => '',
    'parent_id' => '56',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  98 => 
  array (
    'cat_id' => '70',
    'cat_name' => '薄款文胸',
    'measure_unit' => '',
    'parent_id' => '56',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  99 => 
  array (
    'cat_id' => '74',
    'cat_name' => '夏季睡衣',
    'measure_unit' => '',
    'parent_id' => '56',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  100 => 
  array (
    'cat_id' => '71',
    'cat_name' => '无钢圈文胸',
    'measure_unit' => '',
    'parent_id' => '56',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  101 => 
  array (
    'cat_id' => '75',
    'cat_name' => '性感睡衣',
    'measure_unit' => '',
    'parent_id' => '56',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  102 => 
  array (
    'cat_id' => '72',
    'cat_name' => '女士内裤',
    'measure_unit' => '',
    'parent_id' => '56',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  103 => 
  array (
    'cat_id' => '69',
    'cat_name' => '聚拢文胸',
    'measure_unit' => '',
    'parent_id' => '56',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  104 => 
  array (
    'cat_id' => '79',
    'cat_name' => '夹克',
    'measure_unit' => '',
    'parent_id' => '57',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  105 => 
  array (
    'cat_id' => '83',
    'cat_name' => '休闲短裤',
    'measure_unit' => '',
    'parent_id' => '57',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  106 => 
  array (
    'cat_id' => '80',
    'cat_name' => '风衣',
    'measure_unit' => '',
    'parent_id' => '57',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  107 => 
  array (
    'cat_id' => '77',
    'cat_name' => '休闲裤',
    'measure_unit' => '',
    'parent_id' => '57',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  108 => 
  array (
    'cat_id' => '84',
    'cat_name' => 'POLO衫',
    'measure_unit' => '',
    'parent_id' => '57',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  109 => 
  array (
    'cat_id' => '81',
    'cat_name' => '针织衫',
    'measure_unit' => '',
    'parent_id' => '57',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  110 => 
  array (
    'cat_id' => '78',
    'cat_name' => '牛仔裤',
    'measure_unit' => '',
    'parent_id' => '57',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  111 => 
  array (
    'cat_id' => '82',
    'cat_name' => '长袖衬衫',
    'measure_unit' => '',
    'parent_id' => '57',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  112 => 
  array (
    'cat_id' => '92',
    'cat_name' => '登山鞋',
    'measure_unit' => '',
    'parent_id' => '58',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  113 => 
  array (
    'cat_id' => '89',
    'cat_name' => '迷彩裤',
    'measure_unit' => '',
    'parent_id' => '58',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  114 => 
  array (
    'cat_id' => '86',
    'cat_name' => '篮球鞋',
    'measure_unit' => '',
    'parent_id' => '58',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  115 => 
  array (
    'cat_id' => '90',
    'cat_name' => '沙滩鞋',
    'measure_unit' => '',
    'parent_id' => '58',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  116 => 
  array (
    'cat_id' => '87',
    'cat_name' => '帆布鞋',
    'measure_unit' => '',
    'parent_id' => '58',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  117 => 
  array (
    'cat_id' => '91',
    'cat_name' => '钓鱼服',
    'measure_unit' => '',
    'parent_id' => '58',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  118 => 
  array (
    'cat_id' => '88',
    'cat_name' => '羽毛球鞋',
    'measure_unit' => '',
    'parent_id' => '58',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  119 => 
  array (
    'cat_id' => '85',
    'cat_name' => '跑步鞋',
    'measure_unit' => '',
    'parent_id' => '58',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  120 => 
  array (
    'cat_id' => '95',
    'cat_name' => '高跟鞋',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  121 => 
  array (
    'cat_id' => '99',
    'cat_name' => '乐福鞋',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  122 => 
  array (
    'cat_id' => '96',
    'cat_name' => '坡跟单鞋',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  123 => 
  array (
    'cat_id' => '93',
    'cat_name' => '高跟凉拖',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  124 => 
  array (
    'cat_id' => '100',
    'cat_name' => '松糕鞋',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  125 => 
  array (
    'cat_id' => '97',
    'cat_name' => '浅口单鞋',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  126 => 
  array (
    'cat_id' => '94',
    'cat_name' => '平底鞋',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  127 => 
  array (
    'cat_id' => '98',
    'cat_name' => '帆布鞋',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  128 => 
  array (
    'cat_id' => '108',
    'cat_name' => '拉杆包',
    'measure_unit' => '',
    'parent_id' => '60',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  129 => 
  array (
    'cat_id' => '105',
    'cat_name' => '男士钱包',
    'measure_unit' => '',
    'parent_id' => '60',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  130 => 
  array (
    'cat_id' => '102',
    'cat_name' => '手提女包',
    'measure_unit' => '',
    'parent_id' => '60',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  131 => 
  array (
    'cat_id' => '106',
    'cat_name' => '旅行箱',
    'measure_unit' => '',
    'parent_id' => '60',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  132 => 
  array (
    'cat_id' => '103',
    'cat_name' => '女士钱包',
    'measure_unit' => '',
    'parent_id' => '60',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  133 => 
  array (
    'cat_id' => '107',
    'cat_name' => '拉杆箱',
    'measure_unit' => '',
    'parent_id' => '60',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  134 => 
  array (
    'cat_id' => '104',
    'cat_name' => '男士双肩',
    'measure_unit' => '',
    'parent_id' => '60',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  135 => 
  array (
    'cat_id' => '101',
    'cat_name' => '单肩女包',
    'measure_unit' => '',
    'parent_id' => '60',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  136 => 
  array (
    'cat_id' => '118',
    'cat_name' => '套装',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  137 => 
  array (
    'cat_id' => '115',
    'cat_name' => '护肤',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  138 => 
  array (
    'cat_id' => '116',
    'cat_name' => '面膜',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  139 => 
  array (
    'cat_id' => '117',
    'cat_name' => '剃须',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  140 => 
  array (
    'cat_id' => '114',
    'cat_name' => '清洁',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  141 => 
  array (
    'cat_id' => '124',
    'cat_name' => '套装',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  142 => 
  array (
    'cat_id' => '121',
    'cat_name' => '染发',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  143 => 
  array (
    'cat_id' => '122',
    'cat_name' => '造型',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  144 => 
  array (
    'cat_id' => '119',
    'cat_name' => '洗发',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  145 => 
  array (
    'cat_id' => '123',
    'cat_name' => '假发',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  146 => 
  array (
    'cat_id' => '120',
    'cat_name' => '护发',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  147 => 
  array (
    'cat_id' => '127',
    'cat_name' => '颈部',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  148 => 
  array (
    'cat_id' => '131',
    'cat_name' => '套装',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  149 => 
  array (
    'cat_id' => '128',
    'cat_name' => '手足',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  150 => 
  array (
    'cat_id' => '125',
    'cat_name' => '沐浴',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  151 => 
  array (
    'cat_id' => '129',
    'cat_name' => '纤体塑形',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  152 => 
  array (
    'cat_id' => '126',
    'cat_name' => '润肤',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  153 => 
  array (
    'cat_id' => '130',
    'cat_name' => ' 美胸',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  154 => 
  array (
    'cat_id' => '134',
    'cat_name' => '漱口水',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  155 => 
  array (
    'cat_id' => '135',
    'cat_name' => '套装',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  156 => 
  array (
    'cat_id' => '132',
    'cat_name' => '牙膏/牙粉',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  157 => 
  array (
    'cat_id' => '133',
    'cat_name' => '牙刷/牙线',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  158 => 
  array (
    'cat_id' => '143',
    'cat_name' => '套装',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  159 => 
  array (
    'cat_id' => '140',
    'cat_name' => '唇部',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  160 => 
  array (
    'cat_id' => '137',
    'cat_name' => '底妆',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  161 => 
  array (
    'cat_id' => '141',
    'cat_name' => '美甲',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  162 => 
  array (
    'cat_id' => '138',
    'cat_name' => '腮红',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  163 => 
  array (
    'cat_id' => '142',
    'cat_name' => '美容工具',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  164 => 
  array (
    'cat_id' => '139',
    'cat_name' => '眼部',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  165 => 
  array (
    'cat_id' => '136',
    'cat_name' => '香水',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  166 => 
  array (
    'cat_id' => '153',
    'cat_name' => '联通4G',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  167 => 
  array (
    'cat_id' => '150',
    'cat_name' => '小米特供',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  168 => 
  array (
    'cat_id' => '154',
    'cat_name' => '电信4G',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  169 => 
  array (
    'cat_id' => '151',
    'cat_name' => '魅族手机',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  170 => 
  array (
    'cat_id' => '148',
    'cat_name' => '三星盖乐世',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  171 => 
  array (
    'cat_id' => '155',
    'cat_name' => '移动4G',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  172 => 
  array (
    'cat_id' => '152',
    'cat_name' => '华为荣耀',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  173 => 
  array (
    'cat_id' => '149',
    'cat_name' => 'iPhone',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  174 => 
  array (
    'cat_id' => '159',
    'cat_name' => '充电器',
    'measure_unit' => '',
    'parent_id' => '145',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  175 => 
  array (
    'cat_id' => '156',
    'cat_name' => '电池',
    'measure_unit' => '',
    'parent_id' => '145',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  176 => 
  array (
    'cat_id' => '163',
    'cat_name' => '保护套',
    'measure_unit' => '',
    'parent_id' => '145',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  177 => 
  array (
    'cat_id' => '160',
    'cat_name' => '创意配件',
    'measure_unit' => '',
    'parent_id' => '145',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  178 => 
  array (
    'cat_id' => '157',
    'cat_name' => '移动电源',
    'measure_unit' => '',
    'parent_id' => '145',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  179 => 
  array (
    'cat_id' => '161',
    'cat_name' => '手机饰品',
    'measure_unit' => '',
    'parent_id' => '145',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  180 => 
  array (
    'cat_id' => '158',
    'cat_name' => '蓝牙耳机',
    'measure_unit' => '',
    'parent_id' => '145',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  181 => 
  array (
    'cat_id' => '162',
    'cat_name' => '手机耳机',
    'measure_unit' => '',
    'parent_id' => '145',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  182 => 
  array (
    'cat_id' => '175',
    'cat_name' => '户外器材',
    'measure_unit' => '',
    'parent_id' => '146',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  183 => 
  array (
    'cat_id' => '172',
    'cat_name' => '拍立得',
    'measure_unit' => '',
    'parent_id' => '146',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  184 => 
  array (
    'cat_id' => '176',
    'cat_name' => '数码相框',
    'measure_unit' => '',
    'parent_id' => '146',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  185 => 
  array (
    'cat_id' => '173',
    'cat_name' => '运动相机',
    'measure_unit' => '',
    'parent_id' => '146',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  186 => 
  array (
    'cat_id' => '170',
    'cat_name' => '数码相机',
    'measure_unit' => '',
    'parent_id' => '146',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  187 => 
  array (
    'cat_id' => '177',
    'cat_name' => '影棚器材',
    'measure_unit' => '',
    'parent_id' => '146',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  188 => 
  array (
    'cat_id' => '174',
    'cat_name' => '摄像机',
    'measure_unit' => '',
    'parent_id' => '146',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  189 => 
  array (
    'cat_id' => '171',
    'cat_name' => '单反相机',
    'measure_unit' => '',
    'parent_id' => '146',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  190 => 
  array (
    'cat_id' => '169',
    'cat_name' => '体感车',
    'measure_unit' => '',
    'parent_id' => '147',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  191 => 
  array (
    'cat_id' => '166',
    'cat_name' => '智能眼镜',
    'measure_unit' => '',
    'parent_id' => '147',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  192 => 
  array (
    'cat_id' => '167',
    'cat_name' => '运动跟踪器',
    'measure_unit' => '',
    'parent_id' => '147',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  193 => 
  array (
    'cat_id' => '164',
    'cat_name' => '智能手环',
    'measure_unit' => '',
    'parent_id' => '147',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  194 => 
  array (
    'cat_id' => '168',
    'cat_name' => '智能家居',
    'measure_unit' => '',
    'parent_id' => '147',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  195 => 
  array (
    'cat_id' => '165',
    'cat_name' => '智能手表',
    'measure_unit' => '',
    'parent_id' => '147',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  196 => 
  array (
    'cat_id' => '188',
    'cat_name' => '热水器',
    'measure_unit' => '',
    'parent_id' => '178',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  197 => 
  array (
    'cat_id' => '185',
    'cat_name' => '洗衣机',
    'measure_unit' => '',
    'parent_id' => '178',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  198 => 
  array (
    'cat_id' => '189',
    'cat_name' => '消毒柜/洗碗机',
    'measure_unit' => '',
    'parent_id' => '178',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  199 => 
  array (
    'cat_id' => '186',
    'cat_name' => '家庭影院',
    'measure_unit' => '',
    'parent_id' => '178',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  200 => 
  array (
    'cat_id' => '183',
    'cat_name' => '平板电视',
    'measure_unit' => '',
    'parent_id' => '178',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  201 => 
  array (
    'cat_id' => '190',
    'cat_name' => '冷柜/冰吧',
    'measure_unit' => '',
    'parent_id' => '178',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  202 => 
  array (
    'cat_id' => '187',
    'cat_name' => '烟机/灶具',
    'measure_unit' => '',
    'parent_id' => '178',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  203 => 
  array (
    'cat_id' => '184',
    'cat_name' => '空调冰箱',
    'measure_unit' => '',
    'parent_id' => '178',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  204 => 
  array (
    'cat_id' => '191',
    'cat_name' => '电风扇',
    'measure_unit' => '',
    'parent_id' => '179',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  205 => 
  array (
    'cat_id' => '198',
    'cat_name' => '其它生活电器',
    'measure_unit' => '',
    'parent_id' => '179',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  206 => 
  array (
    'cat_id' => '195',
    'cat_name' => '挂烫机/熨斗',
    'measure_unit' => '',
    'parent_id' => '179',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  207 => 
  array (
    'cat_id' => '192',
    'cat_name' => '净化器',
    'measure_unit' => '',
    'parent_id' => '179',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  208 => 
  array (
    'cat_id' => '196',
    'cat_name' => '取暖电器',
    'measure_unit' => '',
    'parent_id' => '179',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  209 => 
  array (
    'cat_id' => '193',
    'cat_name' => '加湿器',
    'measure_unit' => '',
    'parent_id' => '179',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  210 => 
  array (
    'cat_id' => '197',
    'cat_name' => '饮水机',
    'measure_unit' => '',
    'parent_id' => '179',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  211 => 
  array (
    'cat_id' => '194',
    'cat_name' => '吸尘器',
    'measure_unit' => '',
    'parent_id' => '179',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  212 => 
  array (
    'cat_id' => '204',
    'cat_name' => '果蔬解毒机',
    'measure_unit' => '',
    'parent_id' => '180',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  213 => 
  array (
    'cat_id' => '201',
    'cat_name' => '电磁炉',
    'measure_unit' => '',
    'parent_id' => '180',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  214 => 
  array (
    'cat_id' => '205',
    'cat_name' => '养生壶/煎药壶',
    'measure_unit' => '',
    'parent_id' => '180',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  215 => 
  array (
    'cat_id' => '202',
    'cat_name' => '电饼铛/烧烤盘',
    'measure_unit' => '',
    'parent_id' => '180',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  216 => 
  array (
    'cat_id' => '199',
    'cat_name' => '电饭煲',
    'measure_unit' => '',
    'parent_id' => '180',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  217 => 
  array (
    'cat_id' => '206',
    'cat_name' => '其它厨房电器',
    'measure_unit' => '',
    'parent_id' => '180',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  218 => 
  array (
    'cat_id' => '203',
    'cat_name' => '电炖锅',
    'measure_unit' => '',
    'parent_id' => '180',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  219 => 
  array (
    'cat_id' => '200',
    'cat_name' => '微波炉',
    'measure_unit' => '',
    'parent_id' => '180',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  220 => 
  array (
    'cat_id' => '207',
    'cat_name' => '剃须刀',
    'measure_unit' => '',
    'parent_id' => '181',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  221 => 
  array (
    'cat_id' => '214',
    'cat_name' => '其它健康电器',
    'measure_unit' => '',
    'parent_id' => '181',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  222 => 
  array (
    'cat_id' => '211',
    'cat_name' => '健康秤/厨房秤',
    'measure_unit' => '',
    'parent_id' => '181',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  223 => 
  array (
    'cat_id' => '208',
    'cat_name' => '电吹风',
    'measure_unit' => '',
    'parent_id' => '181',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  224 => 
  array (
    'cat_id' => '212',
    'cat_name' => '血糖仪',
    'measure_unit' => '',
    'parent_id' => '181',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  225 => 
  array (
    'cat_id' => '209',
    'cat_name' => '按摩椅',
    'measure_unit' => '',
    'parent_id' => '181',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  226 => 
  array (
    'cat_id' => '213',
    'cat_name' => '计步器/脂肪检测',
    'measure_unit' => '',
    'parent_id' => '181',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  227 => 
  array (
    'cat_id' => '210',
    'cat_name' => '足浴盆',
    'measure_unit' => '',
    'parent_id' => '181',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  228 => 
  array (
    'cat_id' => '220',
    'cat_name' => '监控安防',
    'measure_unit' => '',
    'parent_id' => '182',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  229 => 
  array (
    'cat_id' => '217',
    'cat_name' => '厨卫五金',
    'measure_unit' => '',
    'parent_id' => '182',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  230 => 
  array (
    'cat_id' => '218',
    'cat_name' => '家具五金',
    'measure_unit' => '',
    'parent_id' => '182',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  231 => 
  array (
    'cat_id' => '215',
    'cat_name' => '电动工具',
    'measure_unit' => '',
    'parent_id' => '182',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  232 => 
  array (
    'cat_id' => '219',
    'cat_name' => '电工电料',
    'measure_unit' => '',
    'parent_id' => '182',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  233 => 
  array (
    'cat_id' => '216',
    'cat_name' => '手动工具',
    'measure_unit' => '',
    'parent_id' => '182',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  234 => 
  array (
    'cat_id' => '230',
    'cat_name' => '1段',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  235 => 
  array (
    'cat_id' => '227',
    'cat_name' => '特配奶粉',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  236 => 
  array (
    'cat_id' => '231',
    'cat_name' => '2段',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  237 => 
  array (
    'cat_id' => '228',
    'cat_name' => '孕妈奶粉',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  238 => 
  array (
    'cat_id' => '232',
    'cat_name' => '3段',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  239 => 
  array (
    'cat_id' => '229',
    'cat_name' => 'pre段',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  240 => 
  array (
    'cat_id' => '239',
    'cat_name' => '钙铁锌',
    'measure_unit' => '',
    'parent_id' => '222',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  241 => 
  array (
    'cat_id' => '236',
    'cat_name' => '宝宝零食',
    'measure_unit' => '',
    'parent_id' => '222',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  242 => 
  array (
    'cat_id' => '233',
    'cat_name' => '米粉',
    'measure_unit' => '',
    'parent_id' => '222',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  243 => 
  array (
    'cat_id' => '240',
    'cat_name' => '益生菌',
    'measure_unit' => '',
    'parent_id' => '222',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  244 => 
  array (
    'cat_id' => '237',
    'cat_name' => 'DHA',
    'measure_unit' => '',
    'parent_id' => '222',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  245 => 
  array (
    'cat_id' => '234',
    'cat_name' => '果汁/泥',
    'measure_unit' => '',
    'parent_id' => '222',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  246 => 
  array (
    'cat_id' => '238',
    'cat_name' => '清火开胃',
    'measure_unit' => '',
    'parent_id' => '222',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  247 => 
  array (
    'cat_id' => '235',
    'cat_name' => '面食类',
    'measure_unit' => '',
    'parent_id' => '222',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  248 => 
  array (
    'cat_id' => '246',
    'cat_name' => '奶瓶清洗',
    'measure_unit' => '',
    'parent_id' => '223',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  249 => 
  array (
    'cat_id' => '243',
    'cat_name' => '儿童防晒',
    'measure_unit' => '',
    'parent_id' => '223',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  250 => 
  array (
    'cat_id' => '247',
    'cat_name' => '孕妇护肤',
    'measure_unit' => '',
    'parent_id' => '223',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  251 => 
  array (
    'cat_id' => '244',
    'cat_name' => '防蚊/驱蚊',
    'measure_unit' => '',
    'parent_id' => '223',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  252 => 
  array (
    'cat_id' => '241',
    'cat_name' => '洗衣液/皂',
    'measure_unit' => '',
    'parent_id' => '223',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  253 => 
  array (
    'cat_id' => '245',
    'cat_name' => '爽身粉',
    'measure_unit' => '',
    'parent_id' => '223',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  254 => 
  array (
    'cat_id' => '242',
    'cat_name' => '宝宝沐浴',
    'measure_unit' => '',
    'parent_id' => '223',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  255 => 
  array (
    'cat_id' => '252',
    'cat_name' => '吸奶器',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  256 => 
  array (
    'cat_id' => '249',
    'cat_name' => '驱蚊用品',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  257 => 
  array (
    'cat_id' => '253',
    'cat_name' => '理发器',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  258 => 
  array (
    'cat_id' => '250',
    'cat_name' => '浴室用品',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  259 => 
  array (
    'cat_id' => '254',
    'cat_name' => '防溢乳垫',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  260 => 
  array (
    'cat_id' => '251',
    'cat_name' => '水壶/水杯',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  261 => 
  array (
    'cat_id' => '248',
    'cat_name' => '奶嘴奶瓶',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  262 => 
  array (
    'cat_id' => '255',
    'cat_name' => '安全座椅',
    'measure_unit' => '',
    'parent_id' => '225',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  263 => 
  array (
    'cat_id' => '262',
    'cat_name' => '凉席/蚊帐',
    'measure_unit' => '',
    'parent_id' => '225',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  264 => 
  array (
    'cat_id' => '259',
    'cat_name' => '三轮车',
    'measure_unit' => '',
    'parent_id' => '225',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  265 => 
  array (
    'cat_id' => '256',
    'cat_name' => '手推车',
    'measure_unit' => '',
    'parent_id' => '225',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  266 => 
  array (
    'cat_id' => '260',
    'cat_name' => '儿童家具',
    'measure_unit' => '',
    'parent_id' => '225',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  267 => 
  array (
    'cat_id' => '257',
    'cat_name' => '婴儿床',
    'measure_unit' => '',
    'parent_id' => '225',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  268 => 
  array (
    'cat_id' => '261',
    'cat_name' => '睡袋/抱被',
    'measure_unit' => '',
    'parent_id' => '225',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  269 => 
  array (
    'cat_id' => '258',
    'cat_name' => '餐椅',
    'measure_unit' => '',
    'parent_id' => '225',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  270 => 
  array (
    'cat_id' => '268',
    'cat_name' => '收腹带',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  271 => 
  array (
    'cat_id' => '265',
    'cat_name' => '防辐射服',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  272 => 
  array (
    'cat_id' => '269',
    'cat_name' => '哺乳文胸',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  273 => 
  array (
    'cat_id' => '266',
    'cat_name' => '腰凳',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  274 => 
  array (
    'cat_id' => '263',
    'cat_name' => '孕妇裙',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  275 => 
  array (
    'cat_id' => '270',
    'cat_name' => '孕妇内裤',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  276 => 
  array (
    'cat_id' => '267',
    'cat_name' => '妈咪包',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  277 => 
  array (
    'cat_id' => '264',
    'cat_name' => '打底裤',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  278 => 
  array (
    'cat_id' => '281',
    'cat_name' => '预调酒',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  279 => 
  array (
    'cat_id' => '278',
    'cat_name' => '葡萄酒/果酒',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  280 => 
  array (
    'cat_id' => '279',
    'cat_name' => '黄酒/米酒',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  281 => 
  array (
    'cat_id' => '276',
    'cat_name' => '白酒',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  282 => 
  array (
    'cat_id' => '280',
    'cat_name' => '养生酒',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  283 => 
  array (
    'cat_id' => '277',
    'cat_name' => '啤酒',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
  ),
  284 => 
  array (
    'cat_id' => '287',
    'cat_name' => '麦片谷物',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  285 => 
  array (
    'cat_id' => '284',
    'cat_name' => '豆浆/豆奶粉',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  286 => 
  array (
    'cat_id' => '297',
    'cat_name' => '果味冲调',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  287 => 
  array (
    'cat_id' => '288',
    'cat_name' => '咖啡',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  288 => 
  array (
    'cat_id' => '285',
    'cat_name' => '茶叶',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  289 => 
  array (
    'cat_id' => '282',
    'cat_name' => '蜂蜜',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  290 => 
  array (
    'cat_id' => '286',
    'cat_name' => '奶茶',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  291 => 
  array (
    'cat_id' => '283',
    'cat_name' => '成人奶粉',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  292 => 
  array (
    'cat_id' => '294',
    'cat_name' => '酸奶',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  293 => 
  array (
    'cat_id' => '291',
    'cat_name' => '碳酸饮料',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  294 => 
  array (
    'cat_id' => '295',
    'cat_name' => '风味奶',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  295 => 
  array (
    'cat_id' => '292',
    'cat_name' => '功能饮料',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  296 => 
  array (
    'cat_id' => '289',
    'cat_name' => '果蔬汁',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  297 => 
  array (
    'cat_id' => '296',
    'cat_name' => '植物蛋白饮料',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  298 => 
  array (
    'cat_id' => '293',
    'cat_name' => '纯牛奶',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  299 => 
  array (
    'cat_id' => '290',
    'cat_name' => '茶饮料',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  300 => 
  array (
    'cat_id' => '303',
    'cat_name' => '花果茶',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  301 => 
  array (
    'cat_id' => '300',
    'cat_name' => '龙井',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  302 => 
  array (
    'cat_id' => '304',
    'cat_name' => '养生茶',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  303 => 
  array (
    'cat_id' => '301',
    'cat_name' => '绿茶',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  304 => 
  array (
    'cat_id' => '298',
    'cat_name' => '铁观音',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  305 => 
  array (
    'cat_id' => '305',
    'cat_name' => '其他茶',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  306 => 
  array (
    'cat_id' => '302',
    'cat_name' => '红茶',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  307 => 
  array (
    'cat_id' => '299',
    'cat_name' => '普洱',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  308 => 
  array (
    'cat_id' => '317',
    'cat_name' => '毛巾浴巾',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  309 => 
  array (
    'cat_id' => '314',
    'cat_name' => '蚊帐',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  310 => 
  array (
    'cat_id' => '318',
    'cat_name' => '床垫/床褥',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  311 => 
  array (
    'cat_id' => '315',
    'cat_name' => '凉席',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  312 => 
  array (
    'cat_id' => '312',
    'cat_name' => '床品套件',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  313 => 
  array (
    'cat_id' => '319',
    'cat_name' => '窗帘/窗纱',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  314 => 
  array (
    'cat_id' => '316',
    'cat_name' => '床单被罩',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  315 => 
  array (
    'cat_id' => '313',
    'cat_name' => '被子',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  316 => 
  array (
    'cat_id' => '320',
    'cat_name' => '卧室家具',
    'measure_unit' => '',
    'parent_id' => '307',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  317 => 
  array (
    'cat_id' => '327',
    'cat_name' => '鞋架/衣帽架',
    'measure_unit' => '',
    'parent_id' => '307',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  318 => 
  array (
    'cat_id' => '324',
    'cat_name' => '储物家具',
    'measure_unit' => '',
    'parent_id' => '307',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  319 => 
  array (
    'cat_id' => '321',
    'cat_name' => '客厅家具',
    'measure_unit' => '',
    'parent_id' => '307',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  320 => 
  array (
    'cat_id' => '325',
    'cat_name' => '阳台/户外',
    'measure_unit' => '',
    'parent_id' => '307',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  321 => 
  array (
    'cat_id' => '322',
    'cat_name' => '餐厅家具',
    'measure_unit' => '',
    'parent_id' => '307',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  322 => 
  array (
    'cat_id' => '326',
    'cat_name' => '沙发',
    'measure_unit' => '',
    'parent_id' => '307',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  323 => 
  array (
    'cat_id' => '323',
    'cat_name' => '书房家具',
    'measure_unit' => '',
    'parent_id' => '307',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  324 => 
  array (
    'cat_id' => '333',
    'cat_name' => '茶具/咖啡具',
    'measure_unit' => '',
    'parent_id' => '308',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  325 => 
  array (
    'cat_id' => '330',
    'cat_name' => '厨房配件',
    'measure_unit' => '',
    'parent_id' => '308',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  326 => 
  array (
    'cat_id' => '331',
    'cat_name' => '水具酒具',
    'measure_unit' => '',
    'parent_id' => '308',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  327 => 
  array (
    'cat_id' => '328',
    'cat_name' => '烹饪锅具',
    'measure_unit' => '',
    'parent_id' => '308',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  328 => 
  array (
    'cat_id' => '332',
    'cat_name' => '餐具',
    'measure_unit' => '',
    'parent_id' => '308',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  329 => 
  array (
    'cat_id' => '329',
    'cat_name' => '刀剪菜板',
    'measure_unit' => '',
    'parent_id' => '308',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  330 => 
  array (
    'cat_id' => '336',
    'cat_name' => '筒灯射灯',
    'measure_unit' => '',
    'parent_id' => '309',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  331 => 
  array (
    'cat_id' => '340',
    'cat_name' => '装饰灯',
    'measure_unit' => '',
    'parent_id' => '309',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  332 => 
  array (
    'cat_id' => '337',
    'cat_name' => 'LED灯',
    'measure_unit' => '',
    'parent_id' => '309',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  333 => 
  array (
    'cat_id' => '334',
    'cat_name' => '台灯',
    'measure_unit' => '',
    'parent_id' => '309',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  334 => 
  array (
    'cat_id' => '341',
    'cat_name' => '吊灯',
    'measure_unit' => '',
    'parent_id' => '309',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  335 => 
  array (
    'cat_id' => '338',
    'cat_name' => '落地灯',
    'measure_unit' => '',
    'parent_id' => '309',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  336 => 
  array (
    'cat_id' => '335',
    'cat_name' => '吸顶灯',
    'measure_unit' => '',
    'parent_id' => '309',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  337 => 
  array (
    'cat_id' => '339',
    'cat_name' => '应急灯/手电',
    'measure_unit' => '',
    'parent_id' => '309',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  338 => 
  array (
    'cat_id' => '349',
    'cat_name' => '摆件花瓶',
    'measure_unit' => '',
    'parent_id' => '310',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  339 => 
  array (
    'cat_id' => '346',
    'cat_name' => '相框/照片墙',
    'measure_unit' => '',
    'parent_id' => '310',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  340 => 
  array (
    'cat_id' => '343',
    'cat_name' => '地毯地垫',
    'measure_unit' => '',
    'parent_id' => '310',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  341 => 
  array (
    'cat_id' => '347',
    'cat_name' => '装饰字画',
    'measure_unit' => '',
    'parent_id' => '310',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  342 => 
  array (
    'cat_id' => '344',
    'cat_name' => '沙发垫套/椅垫',
    'measure_unit' => '',
    'parent_id' => '310',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  343 => 
  array (
    'cat_id' => '348',
    'cat_name' => '墙贴/装饰贴',
    'measure_unit' => '',
    'parent_id' => '310',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  344 => 
  array (
    'cat_id' => '345',
    'cat_name' => '帘艺隔断',
    'measure_unit' => '',
    'parent_id' => '310',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  345 => 
  array (
    'cat_id' => '342',
    'cat_name' => '桌布/罩件',
    'measure_unit' => '',
    'parent_id' => '310',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  346 => 
  array (
    'cat_id' => '352',
    'cat_name' => '浴室用品',
    'measure_unit' => '',
    'parent_id' => '311',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  347 => 
  array (
    'cat_id' => '353',
    'cat_name' => '缝纫/针织用品',
    'measure_unit' => '',
    'parent_id' => '311',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  348 => 
  array (
    'cat_id' => '350',
    'cat_name' => '收纳用品',
    'measure_unit' => '',
    'parent_id' => '311',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  349 => 
  array (
    'cat_id' => '354',
    'cat_name' => '洗晒/熨烫',
    'measure_unit' => '',
    'parent_id' => '311',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  350 => 
  array (
    'cat_id' => '351',
    'cat_name' => '雨伞雨具',
    'measure_unit' => '',
    'parent_id' => '311',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  351 => 
  array (
    'cat_id' => '355',
    'cat_name' => '净化除味',
    'measure_unit' => '',
    'parent_id' => '311',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>