<?php echo $this->fetch('library/index_ad1.lib'); ?>
<?php echo $this->fetch('library/index_menu.lib'); ?>
<?php echo $this->fetch('library/index_promote_goods.lib'); ?>
<?php echo $this->fetch('library/index_ad2.lib'); ?>
<?php echo $this->fetch('library/index_ad3.lib'); ?>
<?php echo $this->fetch('library/index_new_goods.lib'); ?>
<?php echo $this->fetch('library/index_hot_goods.lib'); ?>
<?php echo $this->fetch('library/index_ad4.lib'); ?>
<?php echo $this->fetch('library/index_goods_cat.lib'); ?>
<?php echo $this->fetch('library/index_goods_brand.lib'); ?>
<?php echo $this->fetch('library/index_best_goods.lib'); ?>
